"""
Django settings for hms project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


def _env_bool(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


DEBUG = _env_bool("DEBUG", False)

# SECRET_KEY must be provided via .env in any non-DEBUG environment.
SECRET_KEY = os.getenv("SECRET_KEY", "")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-dev-only-do-not-use-in-production"
    else:
        raise RuntimeError(
            "SECRET_KEY is not set. Define it in back/.env before running "
            "with DEBUG=False."
        )

ALLOWED_HOSTS = [
    h.strip() for h in os.getenv("ALLOWED_HOSTS", "").split(",") if h.strip()
]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "django_filters",
    "hms",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise must sit directly after SecurityMiddleware and before
    # everything else: it short-circuits static-file requests so they never
    # touch session, auth, or CSRF handling.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "hms.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hms.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite configuration (backup)
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# MySQL configuration (active)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME", "hms_db"),
        "USER": os.getenv("DB_USER", "root"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "3306"),
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Destination for `manage.py collectstatic`. Without this, collectstatic errors
# out and there is no deployment path - the Django admin and the DRF browsable
# API both need their assets collected in production.
# Already covered by .gitignore (`staticfiles/`).
STATIC_ROOT = BASE_DIR / "staticfiles"

# Django 4.2+ configures storage backends through STORAGES, not the older
# STATICFILES_STORAGE string.
#
# CompressedManifestStaticFilesStorage hashes each filename and writes a
# manifest, so assets can be cached forever and a deploy busts the cache
# automatically. The manifest is built by collectstatic - if it is missing at
# runtime, every {% static %} lookup raises, which is why the Dockerfile runs
# collectstatic at build time.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework settings.
#
# Authentication: JWT (Bearer access + refresh) is the primary mechanism.
# SessionAuthentication is kept so the DRF browsable API + Django admin still
# work for staff. The legacy DRF TokenAuthentication is removed - any existing
# tokens are no longer accepted.
#
# Permissions: IsAuthenticated by default. Reads and writes both require a
# token now. Endpoints that genuinely need to be public (only auth/token
# obtain/refresh in practice) opt in via permission_classes = [AllowAny] on
# the view.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "hms.pagination.CustomPageNumberPagination",
    "PAGE_SIZE": 20,
}

# SimpleJWT settings. Short-lived access tokens force regular refresh.
#
# IMPORTANT - what rotation does and does not buy us:
# `ROTATE_REFRESH_TOKENS` issues a NEW refresh token on each refresh, but with
# `BLACKLIST_AFTER_ROTATION = False` the OLD refresh token stays valid for its
# full REFRESH_TOKEN_LIFETIME. Rotation alone therefore does NOT invalidate a
# stolen refresh token - an attacker holding a copy can keep using it for up to
# a day, in parallel with the legitimate user.
#
# Accepted deliberately for now (see notes/AUTH_FOUNDATION_2026-05-25.md); the
# fix is to install `rest_framework_simplejwt.token_blacklist` in
# INSTALLED_APPS, migrate, and flip the flag below to True.
from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    # Requires the token_blacklist app; see the note above before changing.
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# CORS settings. In dev, default to the local Vite ports. In any other env,
# CORS_ALLOWED_ORIGINS must be provided via .env (comma-separated).
_cors_env = os.getenv("CORS_ALLOWED_ORIGINS", "")
if _cors_env:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_env.split(",") if o.strip()]
elif DEBUG:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:5174",
        "http://127.0.0.1:5174",
    ]
else:
    CORS_ALLOWED_ORIGINS = []

CORS_ALLOW_CREDENTIALS = True

# Hardening flags that auto-enable in non-DEBUG environments. Override
# explicitly in .env if a deployment needs to.
SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# NOTE: `SECURE_BROWSER_XSS_FILTER` was removed. It sets the `X-XSS-Protection`
# header, which Chrome/Edge dropped entirely and Firefox never implemented. It
# protected nothing while reading like it did. A Content-Security-Policy is the
# real replacement (not yet configured - needs a pass to inventory inline
# styles/scripts first).

# Transport security. Both default ON when DEBUG=False and are overridable via
# .env for deployments that terminate TLS upstream (a proxy that already
# redirects, or a health check that must answer over HTTP).
SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", not DEBUG)

# HSTS: tells browsers to refuse plain HTTP for this domain. Starts at 1 hour
# rather than the usual 1 year - a wrong HSTS policy is cached by browsers and
# effectively irreversible for its duration, so raise this deliberately once
# HTTPS is confirmed working end to end (target: 31536000 = 1 year).
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", 3600 if not DEBUG else 0))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", not DEBUG)
# Preload stays OFF: submitting to the browser preload list is a one-way door.
SECURE_HSTS_PRELOAD = _env_bool("SECURE_HSTS_PRELOAD", False)

# Trust the proxy's forwarded-proto header so SECURE_SSL_REDIRECT doesn't cause
# a redirect loop behind a TLS-terminating load balancer. Only enable when a
# proxy you control actually sets this header.
if _env_bool("USE_X_FORWARDED_PROTO", False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Logging.
#
# Everything goes to stdout, nothing to files. On a container platform the
# runtime collects stdout and does the rotating/shipping; writing our own log
# files would put them on a disk that disappears when the container restarts.
LOG_LEVEL = os.getenv("LOG_LEVEL", "DEBUG" if DEBUG else "INFO").upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        # 5xx responses are logged with a full traceback; 4xx stay quiet.
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        # Set to DEBUG locally to see every SQL query the ORM emits - useful
        # for spotting N+1s. Far too noisy to leave on in production.
        "django.db.backends": {
            "handlers": ["console"],
            "level": os.getenv("SQL_LOG_LEVEL", "WARNING").upper(),
            "propagate": False,
        },
        "hms": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}


# Error tracking (Sentry).
#
# Entirely optional: with no SENTRY_DSN set this block does nothing, so local
# development and CI need no account and no network access.
SENTRY_DSN = os.getenv("SENTRY_DSN", "")
if SENTRY_DSN:
    import sentry_sdk  # noqa: E402

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=os.getenv("SENTRY_ENVIRONMENT", "production"),
        # Fraction of requests traced for performance data. Sampling exists
        # because tracing every request costs both money and latency.
        traces_sample_rate=float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.1")),
        # send_default_pii stays OFF deliberately. Turning it on would attach
        # usernames, IP addresses, cookies and request bodies to every event -
        # and this application's request bodies contain patient data.
        send_default_pii=False,
    )
