# Generated by Django 5.2.7 on 2025-10-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ssn", models.CharField(max_length=9, unique=True)),
                ("medicare", models.CharField(max_length=12, unique=True)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("dob", models.DateField()),
                ("telephone", models.CharField(blank=True, max_length=10, null=True)),
                ("citizenship", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=320, null=True)),
                ("occupation", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
