# Generated by Django 4.2.25 on 2025-10-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "ssn",
                    models.IntegerField(
                        db_column="SSN", primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("nurse", "Nurse"),
                            ("doctor", "Doctor"),
                            ("cashier", "Cashier"),
                            ("pharmacist", "Pharmacist"),
                            ("receptionist", "Receptionist"),
                            ("administrative personnel", "Administrative Personnel"),
                            ("security personnel", "Security Personnel"),
                            ("regular employee", "Regular Employee"),
                        ],
                        db_column="Role",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "Employees",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "fid",
                    models.AutoField(
                        db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(db_column="Name", max_length=50, unique=True),
                ),
                ("address", models.CharField(db_column="Address", max_length=100)),
                ("city", models.CharField(db_column="City", max_length=50)),
                ("province", models.CharField(db_column="Province", max_length=25)),
                ("postal_code", models.CharField(db_column="PostalCode", max_length=6)),
                (
                    "phone_number",
                    models.CharField(
                        db_column="PhoneNumber", max_length=10, unique=True
                    ),
                ),
                (
                    "web_address",
                    models.URLField(db_column="WebAddress", max_length=255),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Hospital", "Hospital"),
                            ("CLSC", "CLSC"),
                            ("Clinic", "Clinic"),
                            ("Pharmacy", "Pharmacy"),
                            ("Special installment", "Special installment"),
                        ],
                        db_column="Type",
                        max_length=30,
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(blank=True, db_column="Capacity", null=True),
                ),
                ("gmssn", models.IntegerField(db_column="GMSSN", unique=True)),
            ],
            options={
                "db_table": "Facilities",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"managed": False},
        ),
    ]
